# Pandas Deep-Dive



#### 1. Import Pandas package under the alias pd and Numpy under the alias np.

In [1]:
# your code here
import pandas as pd
import numpy as np

#### 2. Use the `apple_store.sql` file to create a new database in mySQL workbench with that data. Once loaded, try to answer the following questions using mySQL workbench:

 - How many apps are there in the data source?
 - What is the average rating of all apps?
 - How many apps have an average rating no less than 4?
 - How many genres are there in total for all the apps?
 - Which genre is most likely to contain free apps?

In [16]:
import mysql.connector
from getpass import getpass

# Get MySQL credentials
username = "root"
host = "localhost"
database = "apple"

# Get password securely using getpass
password = getpass("Enter your MySQL password: ")

# Connect to the MySQL database
try:
    db_connection = mysql.connector.connect(
        host=host,
        user=username,
        password=password,
        database=database
    )

    # Check if the connection is successful
    if db_connection.is_connected():
        print("Connected to the MySQL database.")

    else:
        print("Failed to connect to the MySQL database.")

except Exception as e:
    print(f"An error occurred: {e}")

Enter your MySQL password: ········
Connected to the MySQL database.


In [19]:
import warnings

warnings.filterwarnings("ignore")

#1. How many apps are there in the data source ?

query_1 = "SELECT COUNT(*) AS id FROM apple.apple_store;"
result_1 = pd.read_sql(query_1, db_connection)

# Extract the count value from the DataFrame
count_apps = result_1.iloc[0, 0]

print(f"There is {count_apps} apps in the data source")

There is 7197 apps in the data source


In [21]:
#2. What is the average rating of all apps ?

query_2 = "SELECT AVG(user_rating) AS average_rating FROM apple.apple_store;"
result_2 = pd.read_sql(query_2, db_connection)

# Extract the count value from the DataFrame
avg_rating = result_2.iloc[0, 0]

print(f"The average rating of all apps is {avg_rating:.2f}")

The average rating of all apps is 3.53


In [22]:
#3. How many apps have an average rating no less than 4?

query_3 = "SELECT COUNT(*) AS count_high_rated FROM apple.apple_store WHERE user_rating >= 4;"
result_3 = pd.read_sql(query_3, db_connection)

# Extract the count value from the DataFrame
count_high_rated = result_3.iloc[0, 0]

print(f"There are {count_high_rated} apps with an average rating of 4 or higher.")

There are 4781 apps with an average rating of 4 or higher.


In [27]:
#4. How many genres are there in total for all the apps?

query_4 = "SELECT COUNT(DISTINCT prime_genre) AS count_genres FROM apple.apple_store;"
result_4 = pd.read_sql(query_4, db_connection)

count_genres = result_4.iloc[0, 0]

print(f"There are {count_genres} unique genres.")

#--

query_unique_genres = "SELECT DISTINCT prime_genre FROM apple.apple_store;"
result_unique_genres = pd.read_sql(query_unique_genres, db_connection)

# Extract the genres from the DataFrame
unique_genres = result_unique_genres['prime_genre'].tolist()

# Print the list of all unique genres
print("List of all unique genres:")
for genre in unique_genres:
    print(genre)

There are 23 unique genres.
List of all unique genres:
Games
Productivity
Weather
Shopping
Reference
Finance
Music
Utilities
Travel
Social Networking
Sports
Business
Health & Fitness
Entertainment
Photo & Video
Navigation
Education
Lifestyle
Food & Drink
News
Book
Medical
Catalogs


In [31]:
# 5. Which genre is most likely to contain free apps? (Alternative version)

# Query to calculate the percentage of free apps in each genre
query_most_likely_genre = """
    SELECT prime_genre,
           COUNT(*) AS total_apps,
           (SUM(price = 0) / COUNT(*)) * 100 AS percentage_free
    FROM apple.apple_store
    GROUP BY prime_genre
    ORDER BY percentage_free DESC
    LIMIT 1;
"""

# Execute the query and store the result in a DataFrame
result_most_likely_genre = pd.read_sql(query_most_likely_genre, db_connection)

#result_most_likely_genre (print df)

# Extract the result / iloc[row_index, column_index]
most_likely_genre = result_most_likely_genre.iloc[0, 0]
percentage_free_in_most_likely_genre = result_most_likely_genre.iloc[0, 2]

print(f"The genre most likely to contain free apps is '{most_likely_genre}' with {percentage_free_in_most_likely_genre:.2f}% free apps.")


The genre most likely to contain free apps is 'Shopping' with 99.18% free apps.


#### 3. Create a SQL connection in this notebook and load the `apple_store` dataset. Assign it to a variable called `data`, which would be a pandas dataframe.

In [32]:
# your code here

# load the apple_store dataset into a Pandas DataFrame
query_load_data = "SELECT * FROM apple_store;"

# Load the data into a Pandas DataFrame
data = pd.read_sql(query_load_data, db_connection)

data.head()

id                                         track_name size_bytes  \
0  281656475                                    PAC-MAN Premium  100788224   
1  281796108                          Evernote - stay organized  158578688   
2  281940292  "WeatherBug - Local Weather, Radar, Maps, Alerts"  100524032   
3  282614216  "eBay: Best App to Buy, Sell, Save! Online Sho...  128512000   
4  282935706                                              Bible   92774400   

  price rating_count_tot rating_count_ver user_rating user_rating_ver  \
0  3.99            21292               26           4             4.5   
1     0           161065               26           4             3.5   
2     0           188583             2822         3.5             4.5   
3     0           262241              649           4             4.5   
4     0           985920             5320         4.5               5   

    prime_genre  
0         Games  
1  Productivity  
2       Weather  
3      Shopping  
4     Reference

#### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [34]:
# your code here

data.head(5)

id                                         track_name size_bytes  \
0  281656475                                    PAC-MAN Premium  100788224   
1  281796108                          Evernote - stay organized  158578688   
2  281940292  "WeatherBug - Local Weather, Radar, Maps, Alerts"  100524032   
3  282614216  "eBay: Best App to Buy, Sell, Save! Online Sho...  128512000   
4  282935706                                              Bible   92774400   

  price rating_count_tot rating_count_ver user_rating user_rating_ver  \
0  3.99            21292               26           4             4.5   
1     0           161065               26           4             3.5   
2     0           188583             2822         3.5             4.5   
3     0           262241              649           4             4.5   
4     0           985920             5320         4.5               5   

    prime_genre  
0         Games  
1  Productivity  
2       Weather  
3      Shopping  
4     Reference

#### 5. Print the summary of the data.

In [35]:
# your code here

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                7197 non-null   object
 1   track_name        7197 non-null   object
 2   size_bytes        7197 non-null   object
 3   price             7197 non-null   object
 4   rating_count_tot  7197 non-null   object
 5   rating_count_ver  7197 non-null   object
 6   user_rating       7197 non-null   object
 7   user_rating_ver   7197 non-null   object
 8   prime_genre       7197 non-null   object
dtypes: object(9)
memory usage: 506.2+ KB


#### 6. Print the number of columns in the data.

In [36]:
# your code here

data.shape[1] # [0] = number of rows, [1] = number of columns

9

#### 7. Print all column names.

In [37]:
# your code here

data.columns

Index(['id', 'track_name', 'size_bytes', 'price', 'rating_count_tot',
       'rating_count_ver', 'user_rating', 'user_rating_ver', 'prime_genre'],
      dtype='object')

#### 8.- Now that we have a general understanding of the data, we'll start working on the challenge questions. How many apps are there in the data source? Print the number of observations of the data.

**Hint**: Your code should return the number 7197.

In [42]:
num_app = data.shape[0]

num_app

7197

#### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [41]:
user_rating = data['user_rating']

user_rating

0         4
1         4
2       3.5
3         4
4       4.5
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196      5
Name: user_rating, Length: 7197, dtype: object

Now you can calculate the average of the `user_rating` data.

**Hint**: Your code should return 3.526955675976101.

In [46]:
# your code here

data['user_rating'] = pd.to_numeric(data['user_rating'], errors='coerce')

average_user_rating = data['user_rating'].mean()
print(f"The average user rating is: {average_user_rating:.2f}")

The average user rating is: 3.53


#### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [47]:
# your code here

user_rating_high = data[data['user_rating'] >= 4]

user_rating_high

id                                         track_name  \
0      281656475                                    PAC-MAN Premium   
1      281796108                          Evernote - stay organized   
3      282614216  "eBay: Best App to Buy, Sell, Save! Online Sho...   
4      282935706                                              Bible   
5      283619399                                   Shanghai Mahjong   
...          ...                                                ...   
7192  1187617475                                              Kubik   
7193  1187682390                                  VR Roller-Coaster   
7194  1187779532              Bret Michaels Emojis + Lyric Keyboard   
7195  1187838770          VR Roller Coaster World - Virtual Reality   
7196  1188375727                       Escape the Sweet Shop Series   

     size_bytes price rating_count_tot rating_count_ver  user_rating  \
0     100788224  3.99            21292               26          4.0   
1     158578688     0           161065               26          4.0   
3     128512000     0           262241              649          4.0   
4      92774400     0           985920             5320          4.5   
5      10485713  0.99             8253             5516          4.0   
...         ...   ...              ...              ...          ...   
7192  126644224     0              142               75          4.5   
7193  120760320     0               30               30          4.5   
7194  111322112  1.99               15                0          4.5   
7195   97235968     0               85               32          4.5   
7196   90898432     0                3                3          5.0   

     user_rating_ver   prime_genre  
0                4.5         Games  
1                3.5  Productivity  
3                4.5      Shopping  
4                  5     Reference  
5                  4         Games  
...              ...           ...  
7192             4.5         Games  
7193             4.5         Games  
7194               0     Utilities  
7195             4.5         Games  
7196               5         Games  

[4781 rows x 9 columns]

Now obtain the length of `user_rating_high` which should return 4781.

In [49]:
# your code here

len(user_rating_high)

4781

#### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [50]:
# your code here

genres = data['prime_genre'].unique()

genres

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

Print the length of the unique values of `genres`. Your code should return 23.

In [51]:
# your code here

len(genres)

23

#### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [52]:
# your code here

top_genres = data['prime_genre'].value_counts().head(3)

top_genres

Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64

#### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [56]:
# Check the data type of the 'price' column
print(data['price'].dtype)


object


In [57]:
# your code here

data['price'] = pd.to_numeric(data['price'], errors='coerce') #coerce errors to NaN for non-convertible values

free_apps = data[data['price'] == 0]

genre_counts = free_apps['prime_genre'].value_counts()

genre_counts.head()

Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Name: prime_genre, dtype: int64

#### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [58]:
# your code here

#proportion_free_apps_by_genre = (data[data['price'] == 0.00]['prime_genre'].value_counts() / data['prime_genre'].value_counts()).sort_values(ascending=False)

# Step 1: Filter data for free apps
free_apps = data[data['price'] == 0.00]

# Step 2: Calculate the count of free apps by genre
free_apps_by_genre = free_apps['prime_genre'].value_counts()

# Step 3: Calculate the total count of apps by genre
total_apps_by_genre = data['prime_genre'].value_counts()

# Step 4: Calculate the proportion of free apps in each genre
proportion_free_apps_by_genre = (free_apps_by_genre / total_apps_by_genre).sort_values(ascending=False)

print(proportion_free_apps_by_genre)


Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64


#### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```

In [59]:
# your code here

average_price_by_genre = data.groupby('prime_genre')['price'].mean()

# Select the genre with the highest average price
most_profitable_genre = average_price_by_genre.idxmax()
average_price_highest = average_price_by_genre.max()

print(f"To make money, a developer should develop apps in the '{most_profitable_genre}' genre with an average price of {average_price_highest:.2f}.")


To make money, a developer should develop apps in the 'Medical' genre with an average price of 8.78.


In [60]:
# Calculate the average price for each genre and sort by descending average price
sorted_genres_by_price = data.groupby('prime_genre')['price'].mean().sort_values(ascending=False)

# Select the genre with the highest average price
most_profitable_genre_alternative = sorted_genres_by_price.index[0] #first genre that appears
average_price_highest_alternative = sorted_genres_by_price.iloc[0] #value related to the first genre

print(f"To make money, a developer should develop apps in the '{most_profitable_genre_alternative}' genre with an average price of {average_price_highest_alternative:.2f}.")


To make money, a developer should develop apps in the 'Medical' genre with an average price of 8.78.


# Challenge - Applying Functions to DataFrames

#### Our next step is to use the apply function to a dataframe and transform all cells.

To do this, we will load a dataset below and then write a function that will perform the transformation.

In [62]:
# Run this code:

# The dataset below contains information about pollution from PM2.5 particles in Beijing 

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00381/PRSA_data_2010.1.1-2014.12.31.csv"
#pm25 = pd.read_csv(url)

In [65]:
import requests

# Download the file
response = requests.get(url)

if response.status_code == 200:
    # Save the content to a local file
    with open("PRSA_data.csv", "wb") as f:
        f.write(response.content)

    # Read the CSV into a DataFrame
    pm25 = pd.read_csv("PRSA_data.csv")

    print(pm25.head())
    
else:
    print("Failed to download the file.")

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0


Let's look at the data using the head() function.

In [66]:
# Your code here:
pm25.head()

No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

The next step is to create a function that divides a cell by 24 to produce an hourly figure. Write the function below.

In [67]:
def hourly(x):
    '''
    Input: A numerical value
    Output: The value divided by 24
        
    Example:
    Input: 48
    Output: 2.0
    '''
    
    # Your code here:
    return x/24
    

Apply this function to the columns Iws, Is, and Ir. Store this new dataframe in the variable pm25_hourly.

In [69]:
# Your code here:

columns_to_apply_hourly = ['Iws', 'Is', 'Ir']

pm25_hourly = pm25.copy()

pm25_hourly[columns_to_apply_hourly] = pm25_hourly[columns_to_apply_hourly].apply(hourly)

pm25_hourly.head()

No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd       Iws   Is  \
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW  0.074583  0.0   
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW  0.205000  0.0   
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW  0.279583  0.0   
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW  0.410000  0.0   
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  0.540417  0.0   

    Ir  
0  0.0  
1  0.0  
2  0.0  
3  0.0  
4  0.0

#### Our last challenge will be to create an aggregate function and apply it to a select group of columns in our dataframe.

Write a function that returns the standard deviation of a column divided by the length of a column minus 1. Since we are using pandas, do not use the `len()` function. One alternative is to use `count()`. Also, use the numpy version of standard deviation.

In [74]:
def sample_sd(x):
    '''
    Input: A Pandas series of values
    Output: the standard deviation divided by the number of elements in the series, minus 1 
        
    Example:
    Input: pd.Series([1,2,3,4])
    Output: 0.3726779962
    '''
    
    # Your code here:
    len_data =x.count()-1
    std_data = np.std(x)
    return std_data/len_data

sample_sd(pd.Series([1,2,3,4]))

0.37267799624996495

In [75]:
# Convert categorical column 'cbwd' to numeric using label encoding

pm25_hourly.apply(sample_sd)

No       2.886817e-01
year     3.226220e-05
month    7.869231e-05
day      2.007924e-04
hour     1.579578e-04
pm2.5    2.204456e-03
DEWP     3.293539e-04
TEMP     2.783578e-04
PRES     2.343194e-04
cbwd     2.140360e-05
Iws      4.754929e-05
Is       7.229519e-07
Ir       1.346183e-06
dtype: float64